### ISSUE TITLE
[Release] Katib 0.10 release for Kubeflow 1.2

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1360]
This is track issue for Katib 0.10 release for Kubeflow 1.2.
Related: https://github.com/kubeflow/kubeflow/issues/5224.

### Main features:
1. Release v1beta1 Katib version.
1. New Trial template design (https://github.com/kubeflow/katib/issues/1208).
1. Extracting metrics in multiple ways (https://github.com/kubeflow/katib/pull/1140).
1. Resume Experiment from volume (https://github.com/kubeflow/katib/issues/1250).
1. Custom CRDs in Trial template (https://github.com/kubeflow/katib/issues/1214).
    - Support MPIJob (https://github.com/kubeflow/katib/pull/1342).
    - Support Tekton (https://github.com/kubeflow/katib/pull/1339).
1. Early Stopping (https://github.com/kubeflow/katib/issues/1330).

### TODOs list for UI update:
- [x] Support new Trial template (https://github.com/kubeflow/katib/issues/1217).
- [x] Support metric strategies (https://github.com/kubeflow/katib/issues/1220).
- [x] Support resume experiment (https://github.com/kubeflow/katib/issues/1221).

### TODOs list for manifest update: 
- [x] Update `kubeflow/manifests` with the latest changes and image versions.

### TODOs list for website update:
- [x] Update all reference to the new v1beta1 APIs.
- [x] New Trial template design (https://github.com/kubeflow/katib/issues/1341).
- [x] Trial metadata injection (https://github.com/kubeflow/katib/issues/1280).
- [x] Default values for Experiment APIs (https://github.com/kubeflow/katib/issues/1286).
- [x] Resume Experiment feature (https://github.com/kubeflow/katib/issues/1292).
- [x] Metrics strategies info (https://github.com/kubeflow/katib/issues/1310).
- [x] Disable ephemeral storage from resources (https://github.com/kubeflow/katib/issues/1358).
- [x] Annotation for istio sidecar (https://github.com/kubeflow/katib/issues/1359).

Let me know if we need to add/remove something.

I the meantime, we are working on new AWS test infra: https://github.com/kubeflow/katib/pull/1356. We try to carry out it before the release.

/area release
/priority p1
/cc @gaocegege @johnugeorge @jlewi @Jeffwan

**Comment by robbertvdg** [comment]
@andreyvelich I deployed the new v1beta1 version with kubeflow manifests, but when deploying the example I get:

`admission webhook "validating.experiment.katib.kubeflow.org" denied the request: Don't support algorithm random: invalid character '"' after object key:value pair.`

I tried deleting both webhooks and reinstalling, however that didn't work.

**Comment by andreyvelich** [comment]
@robbertvdg Can you show me your `katib-config`, please?
```
kubectl get cm katib-config -o yaml -n kubeflow
```
And which example are you running ?
Are you using YAML and `kubectl` to create experiment ?

**Comment by robbertvdg** [comment]
Your comment about the configmap made me realise what was wrong. I added a serviceaccount to the suggestion config, but forgot it was JSON.. I fixed it and now it works 👍 
Thanks for your quick response!

**Comment by andreyvelich** [comment]
@gaocegege @johnugeorge I have released Katib 0.10: https://github.com/kubeflow/katib/releases/tag/v0.10.0.
Please let me know, if we need to add/remove something.

/cc @Jeffwan

**Comment by andreyvelich** [comment]
We have updated the required documentation and Kubeflow manifests.
Katib v0.10.0 has been officially released.
We can close this track issue.

/cc @Jeffwan @gaocegege @johnugeorge
