### ISSUE TITLE
[Release] Katib 0.11 release

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1474]
/kind feature

This is the track issue for Katib 0.11 release.
I think most of the changes are already in upstream. 

### TODOs list:
- [x] Add Katib release script: https://github.com/kubeflow/katib/issues/1466.
- [x] Sync Kubeflow manifest with Katib manifest.
- [x] Generate manifest for the new Katib UI: https://github.com/kubeflow/katib/issues/1469.
- [x] Update training containers in Notebook examples: https://github.com/kubeflow/katib/issues/1475.
- [x] Katib webhooks doc: https://github.com/kubeflow/katib/issues/1266.
- [x] Update boilerplate: https://github.com/kubeflow/katib/pull/1491.
- [x] Fix gRPC build script: https://github.com/kubeflow/katib/pull/1492.

@gaocegege @johnugeorge @yanniszark @kimwnasptd Do we want to include anything else to this release ?

/area release
/priority p1

**Comment by kimwnasptd** [comment]
@andreyvelich could we also include the manifests for the new UI https://github.com/kubeflow/katib/issues/1469?

**Comment by andreyvelich** [comment]
@kimwnasptd, sure.

**Comment by andreyvelich** [comment]
Katib 0.11.0 has been released: https://github.com/kubeflow/katib/releases/tag/v0.11.0.
We can close it.
