### ISSUE TITLE
[Release] Katib 0.12 release

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1597]
This is the track issue for Katib 0.12 release.
We should make the new release before Kubeflow 1.4 to deliver the latest Katib improvements.

### TODOs list

- [ ] Fix problem with unused HPs: https://github.com/kubeflow/katib/issues/1534.
- [ ] Support XGBoostJob: https://github.com/kubeflow/katib/issues/1558.
- [ ] Support Argo Workflow: https://github.com/kubeflow/katib/issues/1081.
- [ ] Modify the default image for Katib UI.
- [ ] Update guides for the new Katib UI: https://github.com/kubeflow/katib/issues/1595.
- [ ] Remove Kubeflow training packages: https://github.com/kubeflow/katib/issues/1596.

@gaocegege @johnugeorge @yanniszark @kimwnasptd @jbottum Do we want to include anything else to this release ?

/area release
/priority p1
