### ISSUE TITLE
RoadMap for v0.4

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#221]
Katib RoadMap for v0.4

- [ ] Support TFJob @gaocegege #39
- [ ] Support TFEvent Metrics @YujiOshima #173
- [ ] Renew UI @YujiOshima  #208 
- [ ] Fix BayseOpt #217
- [ ] Add Test for suggestion Algorithms #42
- [ ] Fix Duplication bug of Metrics and refactor DB @toshiiw  #222

cc @jlewi @gaocegege

**Comment by jlewi** [comment]
/priority p1

Lets use this issue to track getting issues filed for all the items we want done in 0.4 and then close it out.

**Comment by chrisheecho** [comment]
We NEED to do this for this cycle

**Comment by jlewi** [comment]
@YujiOshima I'm closing this issue because it looks like we have individual issues already filed and added to the 0.4 project.
