### ISSUE TITLE
[GSOC] Poject 7 Tracking Issue: Automating Documentation for katib Python SDK

### ISSUE THREAD

**Issue by shivas1516** [kubeflow/katib#2373]
### Objective
Automate the Katib Python SDK reference documentation generation and render it on `kubeflow.org`.

### Tasks
- [x] **Proposal Submission:** Submit the GSOC project proposal as a project proposal in Katib.
- [x] **Review Existing Documentation:** Analyze documentation from other projects for best practices.
- [x] **Local Katib Setup:** Clone Katib repository for kickoff project development.
- [x] **Evaluate Documentation Tools:** Compare Sphinx, MkDocs, Jupyter Book, etc., to choose the best tool for Katib's needs.
- [x] **Configure and Test Documentation Tool:** Set up Sphinx (or chosen tool) for Katib. Could you make sure of the quality and readability of the generated documentation? ([#2392](https://github.com/kubeflow/katib/pull/2392))
- [ ] **Integrate with Kubeflow's Website Repo:** Make the Katib repository a submodule of the website repository and test documentation sharing.
- [ ] **Automate Documentation Updates:** 
  - Write a GitHub Action to automate documentation updates and trigger documentation sharing to the website repository.
  - Script to handle events and update website files.

### Expected Outcomes
- Fully automated, high-quality documentation process.
- Up-to-date documentation on the Katib website.
