### ISSUE TITLE
[Release] Katib 0.18 Roadmap

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#2386]
Let's use this issue as a placeholder for Katib 0.18 roadmap.
We will discuss the items on the upcoming [AutoML WG calls](https://bit.ly/2PWVCkV).

- [x] HP Optimization API for LLMs
- [x] Push-based metrics collection
- [x] Support log-uniform, normal, and other parameter distributions
- [x] Kubernetes 1.28 - 1.31 support: https://github.com/kubeflow/katib/issues/2457
- [ ] https://github.com/kubeflow/katib/issues/2374
- [x] https://github.com/kubeflow/katib/issues/2340
- [ ] https://github.com/kubeflow/katib/issues/2339

**Comment by Electronic-Waste** [comment]
I'm thrilled to see that our GSoC proposals can be turned into a part of the formal release. Let's just do it!

@kubeflow/wg-automl-leads @tariq-hasan @helenxie-bit @shashank-iitbhu .

**Comment by varodrig** [comment]
@andreyvelich  should we close this issue?

**Comment by andreyvelich** [comment]
We haven't released Katib 0.18 yet, so we can keep this tracking issue.

**Comment by Electronic-Waste** [comment]
Remaining PRs to be reviewed/merged in Katib 0.18:

**Features in RoadMap(high priority):**

- [ ] https://github.com/kubeflow/katib/pull/2412
- [ ] https://github.com/kubeflow/katib/pull/2446
- [ ] https://github.com/kubeflow/katib/pull/2423
- [ ] https://github.com/kubeflow/katib/pull/2437

**Fixes:**

- [ ] https://github.com/kubeflow/katib/pull/2496
- [ ] https://github.com/kubeflow/katib/pull/2493
- [ ] https://github.com/kubeflow/katib/pull/2497
- [ ] https://github.com/kubeflow/katib/pull/2482

**Other(optional):**

- [ ] https://github.com/kubeflow/katib/pull/2465
- [ ] https://github.com/kubeflow/katib/pull/2468
- [ ] https://github.com/kubeflow/katib/pull/2488

We need some help to review these PRs, since Kubeflow Platform is releasing 1.10 this week.

cc👀 @kubeflow/wg-automl-leads @kubeflow/wg-manifests-leads @kubeflow/release-team @helenxie-bit @tariq-hasan  @varodrig @Doris-xm @truc0 @AydanPirani @mahdikhashan

**Comment by juliusvonkohout** [comment]
@andreyvelich @Electronic-Waste can you check https://github.com/kubeflow/katib/pull/2510 and https://github.com/kubeflow/manifests/pull/2981 for the Katib release? This is what we need for Kubeflow 1.10 it seems.

**Comment by andreyvelich** [comment]
Katib 0.18 has been released.
Thanks everyone for your contributions!
