### ISSUE TITLE
DB operations for v1alpha2

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#510]
- [x] RegisterExperiment when Experiment CR created #509
- [x] DeleteExperiment when Experiment CR deleted and `RetainHistoricalData` is false #519
- [x] UpdateExperimentStatus when Experiment CR status changed #534
- [x] RegisterTrial when TrialCR created #530 
- [x] DeleteTrial when Trial CR deleted and `RetainHistoricalData` is false (I think when delete experiment, its trials will be deleted in db automatically)
- [x] UpdateTrialStatus when Trial CR status changed #537 
- [x] ReportObservationLog when metricCollector get metrics and insert it into DB. #539 484

**Comment by johnugeorge** [comment]
Can you group these issues? It will be easier to track i feel

**Comment by andreyvelich** [comment]
@hougangliu I will take `RegisterTrial when TrialCR created` from this list.
/cc @johnugeorge

**Comment by richardsliu** [comment]
@hougangliu This is done now, right?

**Comment by hougangliu** [comment]
right, maybe we can close it now
