### ISSUE TITLE
report katib metrics by Prometheus

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#691]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Metrics being targeted to track by HTTP endpoint in Prometheus metrics format: 
Report katib metrics:
- [x] Experiment/Trial  creation/deletion #870
- [x] Trial/Experiments success/failure #870
- [x] Katib-controller metrics such as Total number of reconcilation errors per controller, Length of reconcile queue per controller, Reconcilation latency,Usual resource metrics such as CPU, memory usage, file descriptor usage,Go runtime metrics such as number of Go routines, GC duration (the default metrics support has been added in controller-runtime 0.1.8+) #717

**Comment by hougangliu** [comment]
v0.1.18 controller-runtime had introduced [prometheus metrics to internal controller](https://github.com/kubernetes-sigs/controller-runtime/pull/132), and v0.1.18 controller-runtime depends on kubernetes-1.12.3 package api as [here](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.1.8/Gopkg.toml)
for now pytorch-operator and tf-operator depend on kubernetes-1.11.2

If we upgrades controller-runtime to v0.1.18 or above in kabit, it will reduce much effort of this feature. controller-runtime v0.1.18 has conflict dependence with  pytorch-operator and tf-operator, which katib depends on both.

@richardsliu @gaocegege @johnugeorge 
do pytorch-operator and tf-operator repo have any plan to upgrade kubernetes lib dependence?

**Comment by gaocegege** [comment]
I really suggest updating the dep version of the operators, but I am not sure if we can.

/cc @richardsliu

**Comment by johnugeorge** [comment]
I can try
